### ISSUE TITLE
Different id's from Toons json file

### ISSUE THREAD

**Issue by jerver** [cyberjunky/home-assistant-toon_smartmeter#7]
This custom component is not working anymore in my case. I added Toon op Zon and after this the webservices on my Toon show different ID's in the json file 

  dev_7.1 	gas					HAE_METER_v3_1
  dev_7.4 	verbruik hoog			HAE_METER_v3_4
  dev_7.5 	teruglevering hoog		HAE_METER_v3_5
  dev_7.6 	verbruik laag			HAE_METER_v3_6
  dev_7.7 	teruglevering hoog		HAE_METER_v3_7

Can you please help me by adapting the code so it works with these values as well? Thank you.

**Comment by cyberjunky** [comment]
Can you post result from this browser output? You can mask serial numbers if needed,
http://<toon_ip:<toon_port>/hdrv_zwave?action=getDevices.json

**Comment by jerver** [comment]
This is the result. Thx for checking. 

[json output.txt](https://github.com/cyberjunky/home-assistant-toon_smartmeter/files/4678860/json.output.txt)

**Comment by cyberjunky** [comment]
@jerver Thanks. I guess the last one should be 'laag' instead of 'hoog' (double):
dev_7.1 gas HAE_METER_v3_1
dev_7.4 verbruik hoog HAE_METER_v3_4
dev_7.5 teruglevering hoog HAE_METER_v3_5
dev_7.6 verbruik laag HAE_METER_v3_6
dev_7.7 teruglevering laag HAE_METER_v3_7

I have implemented some stuff, can you try latest version 1.0.7 and if it still fails somehow, post the debug info (you can mask out the uuid etc)

**Comment by jerver** [comment]
Yep, The last one is "teruglevering laag" indeed. (copy-paste error). Somehow it seems that if you disconnect the poweradapter and connect it again the dev_ number changes. 
Anyway, its working now. Thank you for your swift help. It is very much appreciated.
