### ISSUE TITLE
Total use of the day

### ISSUE THREAD

**Issue by olraccus** [cyberjunky/home-assistant-toon_smartmeter#8]
Hi Cyberjunky,

Don't know if this is the right way to get in touch, just started github and also Home Assistant.I use your addon via HACS, Toon smart meter

I wonder if it is possible to show the use of electricity throughout the day and current gas consumption.

For the rest, I think the addon works well, looks great.

(Ps, if this message does not belong here, please delete it)

**Comment by cyberjunky** [comment]
If you mean the total gas and electricity per day in sensors, it's not provided but there are other components which can add this.
Something like this: https://github.com/jeroenterheerdt/HADailySensor
Not tested.

**Comment by olraccus** [comment]
Thnx !

I thought is could work because Toon unrooted does…

Kind regards,
Carlo

**Comment by cyberjunky** [comment]
Its not in de data exposed, the Toon calculates this itself I guess.

**Comment by kurniawan77** [comment]
You can use the "Utility Meter" integration built in Home Assistant:

https://www.home-assistant.io/integrations/utility_meter/

**Comment by cyberjunky** [comment]
Closed, best suggestion is looking into Utility Meter.

**Comment by itguy013** [comment]
Hi,

I have the same issue as above. I tried to use the utility meter and the integration sensor, but then i got to see this:
NaN kWatth

It's only with the toon, because i did exactly the same setup with bij zwave plugs, but the integration sensor and utility meter works fine with them. Anyone ideas how to fix this or how they are collecting daily data with toon rooted?
